touch "./results/1.txt"
touch "./results/2.txt"
touch "./results/3.txt"
touch "./results/4.txt"
touch "./results/5.txt"
touch "./results/6.txt"
touch "./results/7.txt"
touch "./results/8.txt"

echo "библиотечная функция построения" > "./results/1.txt"
echo "Алгоритм ЦДА" > "./results/2.txt"
echo "Брезенхем с действительными числами" > "./results/3.txt"
echo "Брезенхем с целыми числами" > "./results/4.txt"
echo "Брезенхем с устранением ступенчатости" > "./results/5.txt"
echo "Алгоритм ВУ" > "./results/6.txt"
echo "Исследование временных характеристик" > "./results/7.txt"
echo "Исследование ступенчатых характеристик" > "./results/8.txt"